server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://192.168.56.101:3306/home_decoration?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: baiguo123

  redis:
    database: 0
    host: 192.168.56.101
    port: 6379
    password: baiguo123
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 5000


mybatis:
   configuration:
      map-underscore-to-camel-case: true
file:
  uploadFolder: C:/Users/shenz/Desktop/pictures/
